### ISSUE TITLE
名前

### ISSUE THREAD

**Issue by c0a21012** [c0a21032/ProjExD#11]
https://github.com/c0a21032/ProjExD/blob/0a2f13e1df7b82d0481838dc5cce27f7ae949cd7/ex03/maze.py#L32
触れたらゴールできるこうかとんなのでenemyから名前を変えたほうが良いと思う

**Comment by c0a21032** [comment]
変更がめんどくさいので言い訳をすると、星を集めて力を蓄えて敵を倒す、というストーリーにしておきます。
