### ISSUE TITLE
質問

### ISSUE THREAD

**Issue by Masa-Yaga** [c0a21032/ProjExD#7]
https://github.com/c0a21032/ProjExD/blob/c3c7c25410139c4bd0f6c9001d953e3e07048386/ex02/calc.py#L44

自分の頭が悪いので理解できませんでした。
ここの()の中の関数？について解説お願いします。

**Comment by c0a21032** [comment]
enzanのkeyがnumに入るたびに、iに1プラスされます。行の指定で使っています

**Comment by Masa-Yaga** [comment]
行の指定理解しました。ありがとうございます。
